// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPS
{
        public const string achievement_war = "CgkIx5CvwKwMEAIQBA"; // <GPGSID>
        public const string achievement_ghostbusters = "CgkIx5CvwKwMEAIQAg"; // <GPGSID>
        public const string achievement_unlucky = "CgkIx5CvwKwMEAIQAQ"; // <GPGSID>
        public const string achievement_are_you_serious = "CgkIx5CvwKwMEAIQAA"; // <GPGSID>
        public const string achievement_this_is_just_the_beginning = "CgkIx5CvwKwMEAIQAw"; // <GPGSID>

}

